/******************************************************************************
 *                                                                            *
 * Copyright 2020 Meng-Shan Jiang                                             *
 *                                                                            *
 * Licensed under the Apache License, Version 2.0 (the "License");            *
 * you may not use this file except in compliance with the License.           *
 * You may obtain a copy of the License at                                    *
 *                                                                            *
 *    http://www.apache.org/licenses/LICENSE-2.0                              *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 *                                                                            *
 *****************************************************************************/

#include "test.h"

/********************** MUL G **********************/
typedef struct
{
    char *scalar; /* hex */
    char *x;      /* (scalar*G).x, mont, hex */
    char *y;      /* (scalar*G).y, mont, hex */
    char *z;      /* (scalar*G).z, mont, hex */
}MULG_TEST_VEC;

/* test vectors are generated by test.py */
static const MULG_TEST_VEC mulg_test_vec[] =
{
    /* 1 */
    {
        "0",
        "0",
        "0",
        "0",
    },
    /* 2 */
    {
        "1",
        "9981e643e9089f48979f48c033fd129c231e295329bc66dbd7362e5a487e2097",
        "cf3f851fd4a582d670b6b59aac19c1368dfc5d5d1f1dc64db15ea6d2d3dbabe2",
        "00000000000000000000000000000000000000000000000000000001000003d1",
    },
    /* 3 */
    {
        "1A",
        "941d164e08257d0b81a4f203d3f67399d6b8d5f8c7ad38ba546509a2c70bc742",
        "7682a199bf8f4e890c29e912d78c27a1596b81c83a8fde9f06bef4790eae211",
        "797f61093b2d72bae3937dd81a937af3bf4946096d1b4282ef45c75da7ec6584",
    },
    /* 4 */
    {
        "FFF",
        "5864844f9b5d081b98d8cba8a73c67ba03b525431c2cefb6a26dba7bc1f636b6",
        "e758432a46fcecb8978ce18b9018ffcf2ff8e7f451320aae6c1314e889eac5d2",
        "ade71722e310e5937366406257a96ab15ddf11e34065f5ef96c141a39bb423d2",
    },
    /* 5 */
    {
        "12345678",
        "39e58d4c0d2c61b27143fe540ea6668b523d67ed471a304bf95a415c01d0c872",
        "e719a96a8de34d6a66593d3177ffcbbe117030367b589df336ffde20b3b10457",
        "125ccceddf99d24d52c057598ff221c68391a5b3d42c5f01e2b5e3f3da3b668a",
    },
    /* 6 */
    {
        "FEDCBA9876543210",
        "c39e0258e50e9dd462b2efa1cca697ff51d499434c01efb5c12a4b5ee16d70cc",
        "de6c832db0598937fc8d018a30460cba22f9441a79af3cbf0a526c1eb1862c06",
        "9715d9f1cd5e1fc48c59f7f27b84ef8ad71840041eee1e4d98d2e961cb5a6320",
    },
    /* 7 */
    {
        "FEDCBA98765432100123456789ABCDEF",
        "4a12c968d1e1a8af879bb9e3c56f3654e7edf208801f89ab5f8b1e5b848f743f",
        "12e548479ad75749e7b156937903eff134e41b838ba11cd6a5d3d4d04930ef59",
        "a954f25fdfec334aad9ff65aa64012e64c3f9f1a6cb1bb4857479308b4c47ab4",
    },
    /* 8 */
    {
        "FFEEDDCCBBBAA9987766554433221100",
        "442fe3638b1feaee14c4af556fb625965ca2368cc20d0369136beac85bffb16a",
        "c21b5279c50a9df52f18713f957d1e052dc8749de16d69b3ba7c574ac6435e6b",
        "c79a57570614ab8454fd344c2c596ed9caa87b25f52823e2095fb88e7a927185",
    },
    /* 9 */
    {
        "142857142857142857142857142857142857",
        "32d10ad6ebc2e80e93e83385453c7da3d8b75b5b5bb77061f3fe27a6bdbac2c4",
        "c3b773b2e17dcee98e1eca43ad3e45f8e2f9304ab3d9f8f8f4a07498f2d0f017",
        "13d65d7ef153cb19689962b887f190c5bbea0726b01a04cc4973eba0bcc1cb92",
    },
    /* 10 */
    {
        "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
        "4b03db280d7843b7795c1051e72a6d61f1d3ebb88bcca4f2227bb1c6f89fc848",
        "29a52229b5a2f81ef9fdd67cfde49e89d9d5987fa5251431f69130a04101a881",
        "df73d3d79e4bc93f87d103e4576469837685cb2e337482bd76cec108a3d99d58",
    },
    /* 11 */
    {
        "13579BDF2468ACE147AD0369CF258BEEEEEEEEEEEEEEE",
        "b7a0d1fe42c634189eb2cd520553985e33541cb528c18b5407e487f424a924ce",
        "0fd06868454a03ca809d7f48501c74fe7cb917467a283d14b496ad8a8c1b6c93",
        "a47cf510fb3ebd224929f14ef5d3ef3e095f949f09836bc5bf16e7298b4ff4ce",
    },
    /* 12 */
    {
        "17247080AB5A008DE0A0BD0136EFD09AD9081B36FF06348BC",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
    },
    /* 13 */
    {
        "81ADEE20FFFFFFFFFFF507AE8FCB908A0A8FC908EADDD2408D3BBBBBBB598F08",
        "52ed43012944ea93e54898769398746bd1387bfcbb26232b961108e948c95f7c",
        "ef4f31a2052528ab8d45f143d18d68369606a0694d239ff3b3c79f8c318a3a7d",
        "c2067fb555c56b8e3bd991a609f71cbe091ac6995d76c593cc235ad16664a14a",
    },
    /* 14 */
    {
        "9999999999999999999999999999999999999999999999999999999999999999",
        "a8d2045a1329f7cc9cf9d2ea9a12323cf453491c9b150ab211efcec772cfad7e",
        "18506390dc5432872447c86042df0b2a40e8d655bc8ccf7eaa8c6ba8025c8989",
        "4bb9a7ba9e0ed51efdabc0e4f1035b26dbbe3e7e44c4b09c5a80198c7a096e4d",
    },
    /* 15 */
    {
        "ABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABAB",
        "4d57ba73f902fd0765560486709a9724e193e2926a2d364a615947399208aeac",
        "c003e5f1b9ba55cc05e61df3235cf1e069fdd47e2c17f570630d12ce1dfc3147",
        "9ca8e4524f03b0388d77447329dd71280f418db13c5815eb60d041dcf61fe2e2",
    },
    /* 16 */
    {
        "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
        "19743eb2cc7c085cd4ac7f59c70968bee64938ec9d727efd43e14cb5437ce937",
        "61da802c9a1785b02990cefe705daf4c729b0f9c80b522b66f1b645ac18029c3",
        "adb584b3ab829cedb82fafae8e16d1d8dc74d5f3ed106b7da5265925c7ce7ff9",
    },
    /* 17 */
    {
        "DBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDBDB",
        "bc274f64804090b19f29849091eb90beedab2282d0479ea4380614b9ba76522f",
        "97c07a00546316350e5c1927031a7513ef848eba9646d9e80de58dd6fe60ef65",
        "92467a74bf08338f8559b249a9dda12c020c9f84da48658d54743b1752233280",
    },
    /* 18 */
    {
        "E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2E2",
        "a0ca412d03c99a87060afcd8a3b083be80b2253ddc6385c8a445307993eaf11e",
        "4993f0e989ee410cee1fced3df7813e4bd22b5ebe4e333c8e619cd13185efc0a",
        "5de895c03ddd0e081d42a707722e5a8e88851b1ead6c995144b3678192c65eef",
    },
    /* 19 */
    {
        "F2839FD98010AABC08365DEEA010DB90E8A8CD00328623332ACB289560D558AB",
        "5b91829bf07ac8ce26056396cac8b2157145e276c37eacb4042f137e43707344",
        "2e796774a9747d7540c46a6fa63191f1b535363085feaca50ade97422cb20a15",
        "b00f12690811b5991bdd76a25f174746b20a6a3dcaf6d55b7256ee5bab67395f",
    },
    /* 20 */
    {
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000000000000000000000000",
        "34a3fd1338a5133d5447857923fa7797a77033c7cea5e9a26fe1db4456a5c56d",
        "e88f01e9a2aa6fda7ecefb882d4a51a2cc3d95893ef6a3b53f08ab63aa97d7a3",
        "256010bd5469bb4bb52eec89ca5a36533454f9840b71ed673eeb29e1a991fb81",
    },
    /* 21 */
    {
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141",
        "0",
        "0",
        "0",
    },
};

static int secp256k1_mul_g_test()
{
    int i;
    POINT256 r1, r2;
    BN_ULONG scalar[P256_LIMBS];

    for (i = 0; i < sizeof(mulg_test_vec) / sizeof(MULG_TEST_VEC); i++) {
        fp256_set_hex(scalar, (unsigned char*)mulg_test_vec[i].scalar, strlen((const char*)mulg_test_vec[i].scalar));
        fp256_set_hex(r1.X, (unsigned char*)mulg_test_vec[i].x, strlen((const char*)mulg_test_vec[i].x));
        fp256_set_hex(r1.Y, (unsigned char*)mulg_test_vec[i].y, strlen((const char*)mulg_test_vec[i].y));
        fp256_set_hex(r1.Z, (unsigned char*)mulg_test_vec[i].z, strlen((const char*)mulg_test_vec[i].z));
        
        if (secp256k1_point_is_on_curve(&r1) == 0) {
            printf("mul_g test %d, point r1 is not on curve\n", i+1);
        }
        
        /* r2 = scalar * G */
        secp256k1_scalar_mul_gen(&r2, scalar);
        if (secp256k1_point_is_on_curve(&r2) == 0) {
            printf("mul_g test %d, point r2 is not on curve\n", i+1);
        }

        /* compare r1, r2 */
        if (secp256k1_point_cmp(&r1, &r2) != 0) {
            printf("mul_g test %d fail\n", i+1);
            return CRYPTO_ERR;
        }
    }
    
    printf("mul_g test pass\n");
    return CRYPTO_OK;
}

/********************** MUL OTHER POINT **********************/
typedef struct
{
    char *scalar;  /* hex */
    char *px;      /* point.x, mont, hex */
    char *py;      /* point.y, mont, hex */
    char *pz;      /* point.z, mont, hex */
    char *rx;      /* (scalar*point).x, mont, hex */
    char *ry;      /* (scalar*point).y, mont, hex */
    char *rz;      /* (scalar*point).z, mont, hex */
}MULP_TEST_VEC;

/* test vectors are generated by test.py */
static const MULP_TEST_VEC mulp_test_vec[] =
{
    /* 1 */
    {
        "0",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
        "0",
        "0",
        "0",
    },
    /* 2 */
    {
        "1",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
    },
    /* 3 */
    {
        "DDF2",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
        "a118faaadb3f0e0b7663ef2e443dbf4997a8e4a23d4062071b95e05e2a10369a",
        "219ea6a057d53c822bc66f0b91cc64a100f96509526d99e64b13f932d6691d93",
        "d650a64442e8e0c71c532caa50ccc62ad540e58feff8c5e704bfac85fea09ae1",
    },
    /* 4 */
    {
        "BC08365DEEA010DB90E8A8CD00328623332ACB",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
        "918463d29b8670335d4d23f0b097530ffbeeaa3d2c907bd89388ec81a6e2d497",
        "013e7eda4cefb3221a17b55b8c59f038f8537184418eda67224b77aee5aac6bd",
        "ae17b2c3966712f9606761bf12b1e498dd6033b5accd70ad035a802d4536f16f",
    },
    /* 5 */
    {
        "F2839FD98010AABC08365DEEA010DB90E8A8CD00328623332ACB289560D558AB",
        "23c5835633f331bac25a9640c7abaaf27cd8e846b99d42f7dd9b11a762c3fd76",
        "e623f2e4ca492bad67932f70159084b36d759dda150facc00282980c94aa8203",
        "5dd36cb93a3d5adad9233274e58d30accdfd76eb2d67912b457dc1c9888d1b71",
        "80ef7cbee7b2de3db748023937232b9279300ec438a7e3a90f72de092d61401a",
        "9d7183c3278e23a7fae2f7ef81b8763cbf239703b5cfdd612ae0cc76a8c8fb73",
        "6e5b0aacfdb32dea69eace00b220e31f825fdd999fa316b6ea9982dd4a4ee813",
    },
    /* 6 */
    {
        "192837465FFFFFFFFFFF",
        "80ef7cbee7b2de3db748023937232b9279300ec438a7e3a90f72de092d61401a",
        "9d7183c3278e23a7fae2f7ef81b8763cbf239703b5cfdd612ae0cc76a8c8fb73",
        "6e5b0aacfdb32dea69eace00b220e31f825fdd999fa316b6ea9982dd4a4ee813",
        "bb392efc85d8540f8d2ffd55672e7c043403edb199885f05da0c8b779e0d9eae",
        "3cecea071a8e38ac4bb6a93bc373c64dc84cbd845d586ad5a2897c8551c338de",
        "7920fbdc0716370b03038d2f9352c3f64493cfa607e00ec5e98266981da4e212",
    },
    /* 7 */
    {
        "777777777777777777777777777777777777777777",
        "80ef7cbee7b2de3db748023937232b9279300ec438a7e3a90f72de092d61401a",
        "9d7183c3278e23a7fae2f7ef81b8763cbf239703b5cfdd612ae0cc76a8c8fb73",
        "6e5b0aacfdb32dea69eace00b220e31f825fdd999fa316b6ea9982dd4a4ee813",
        "da4be6be42d8ff8e151d357b982191979b30894d828238c20ca51f11a65da880",
        "be97d8d3fc56fa1d538bcf3ad879b71451dcc21d3a4a4b724f8f0ab835ba774e",
        "2e6b976723f75c4fcf6d6e93c7c53388b5f67972f8ff53fe35c3584fdf42ff96",
    },
    /* 8 */
    {
        "EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "80ef7cbee7b2de3db748023937232b9279300ec438a7e3a90f72de092d61401a",
        "9d7183c3278e23a7fae2f7ef81b8763cbf239703b5cfdd612ae0cc76a8c8fb73",
        "6e5b0aacfdb32dea69eace00b220e31f825fdd999fa316b6ea9982dd4a4ee813",
        "250bcc1cde09fae0fc4726d9d2450ae48111f92ef3d89d90ce283034e39ec246",
        "240bd9d4fbe7d879cd51e2ed62322d6247d60086b1493cdb7dfc6afeac558bdf",
        "1e49b98d4b6e8194e43e76d28437608550925604d725efac401bf00281e4d5e1",
    },
    /* 9 */
    {
        "888",
        "250bcc1cde09fae0fc4726d9d2450ae48111f92ef3d89d90ce283034e39ec246",
        "240bd9d4fbe7d879cd51e2ed62322d6247d60086b1493cdb7dfc6afeac558bdf",
        "1e49b98d4b6e8194e43e76d28437608550925604d725efac401bf00281e4d5e1",
        "8cf84dd408ad5395164edde420a5b64acdc636a0487c86c3e44ee8604c9559fb",
        "099202d999221eb1f217d853ed61761175fd52ccebca917d3f69f32d7ec8dd52",
        "8a3e260ef0fe8d351ac7a71d61ed8ca9c05d29b2f720ca67957ad7061027d254",
    },
    /* 10 */
    {
        "10000000000000000000000000000000000000000000000",
        "250bcc1cde09fae0fc4726d9d2450ae48111f92ef3d89d90ce283034e39ec246",
        "240bd9d4fbe7d879cd51e2ed62322d6247d60086b1493cdb7dfc6afeac558bdf",
        "1e49b98d4b6e8194e43e76d28437608550925604d725efac401bf00281e4d5e1",
        "262a09cf12004af4b63d67596aa796e4881d3c03cdcc92ef04cd78a790896571",
        "88c16f6a388802bd9638e430b616c6d512127738154360d4a4a920a445765d18",
        "022d22968251d8e70830c63a3b7786b949ce3baee0e64268b47cad36fbed94f5",
    },
    /* 11 */
    {
        "FFFFFFFFFFFFFFFFF10000000000000000000000000000000000000000000000",
        "250bcc1cde09fae0fc4726d9d2450ae48111f92ef3d89d90ce283034e39ec246",
        "240bd9d4fbe7d879cd51e2ed62322d6247d60086b1493cdb7dfc6afeac558bdf",
        "1e49b98d4b6e8194e43e76d28437608550925604d725efac401bf00281e4d5e1",
        "e3447c647e2ae71b7665d5c9f5fb951607c2d59d7d56069ac36156fe7eb0e49b",
        "d7cda15094e78437d8ca4304b80972d2254770dada9fb20a443c4eff8407bbe0",
        "35c70b94093470e974940d2696439d7cbba9ac5a7c44f92947c2137bc6f79e08",
    },
    /* 12 */
    {
        "22222222222",
        "e3447c647e2ae71b7665d5c9f5fb951607c2d59d7d56069ac36156fe7eb0e49b",
        "d7cda15094e78437d8ca4304b80972d2254770dada9fb20a443c4eff8407bbe0",
        "35c70b94093470e974940d2696439d7cbba9ac5a7c44f92947c2137bc6f79e08",
        "2661b2818655bc2f9c2cba8af3398fe7f2f56fbc00a895260e6fd43c57372db8",
        "0aee8a5471b6ff2edcc34a5e036886def6778635a1b891642bf0519b440f2d13",
        "8b79322eb4b8f33a5eb57b893ee76b8727b571e93daac29ea199d2cf42fbc23e",
    },
    /* 13 */
    {
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF2F2222222222",
        "e3447c647e2ae71b7665d5c9f5fb951607c2d59d7d56069ac36156fe7eb0e49b",
        "d7cda15094e78437d8ca4304b80972d2254770dada9fb20a443c4eff8407bbe0",
        "35c70b94093470e974940d2696439d7cbba9ac5a7c44f92947c2137bc6f79e08",
        "ca595810309e3542d9d02a1a15938de6b2fbe132abf348c94f958b52489bbfab",
        "7719d40b64fb8be5e33e78adc4e2b75e032e271be38dedc7f7b574b79fcb1bf6",
        "b9205b78f04867325d16667e899145a4b07531788bde2c29d51448861f8d5047",
    },
    /* 14 */
    {
        "CCCCCCCCC",
        "ca595810309e3542d9d02a1a15938de6b2fbe132abf348c94f958b52489bbfab",
        "7719d40b64fb8be5e33e78adc4e2b75e032e271be38dedc7f7b574b79fcb1bf6",
        "b9205b78f04867325d16667e899145a4b07531788bde2c29d51448861f8d5047",
        "53f3e763901547a8ec4ad4c5ddc3110fe64635010ec12c12c4ef2815a08ed817",
        "527a109a6c90f14102b050147d9fd026c35bc9a3a79d9686ac88e646f3c46028",
        "a0eccfd35af9c3a98943c1dae84d716974d17d8a40a2d08338d964d07a7278a7",
    },
    /* 15 */
    {
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
        "ca595810309e3542d9d02a1a15938de6b2fbe132abf348c94f958b52489bbfab",
        "7719d40b64fb8be5e33e78adc4e2b75e032e271be38dedc7f7b574b79fcb1bf6",
        "b9205b78f04867325d16667e899145a4b07531788bde2c29d51448861f8d5047",
        "4e08a2caf1292e18b964688d0dcc066c9d9edd1835e7949ee32a161db533df02",
        "e7ddaa946be4cf701ea1f4b06b3a8eb11355ac42241e3695df522e58187d460c",
        "9b000581611f0030821b0407c6e5cb1587981966d11f87ab809c4c6b357cf509",
    },
    /* 16 */
    {
        "AAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAFAAAAAFAA",
        "4e08a2caf1292e18b964688d0dcc066c9d9edd1835e7949ee32a161db533df02",
        "e7ddaa946be4cf701ea1f4b06b3a8eb11355ac42241e3695df522e58187d460c",
        "9b000581611f0030821b0407c6e5cb1587981966d11f87ab809c4c6b357cf509",
        "16e1d165fb05c057b417ba35aaa47f989f4dec3dd4d23142649405114dfed7c7",
        "c17410189d20572cd2f6441f3c40422d80bd33e16f749137a84a0fce1da2462d",
        "b756af144e9e55c65e7894dd3a90af1cdafa68ef6677060fc754f3e25f47b851",
    },
    /* 17 */
    {
        "FEDCBAFEDCBAFEDCBAFEDCBFEDCBAFEDCBAFEDCBAFEDCBAFEDCBAFEDCAFEDCBA",
        "4e08a2caf1292e18b964688d0dcc066c9d9edd1835e7949ee32a161db533df02",
        "e7ddaa946be4cf701ea1f4b06b3a8eb11355ac42241e3695df522e58187d460c",
        "9b000581611f0030821b0407c6e5cb1587981966d11f87ab809c4c6b357cf509",
        "0d2fadfb6228aab61281ac711dfc405889d654394a7afb375a82ab00c6205cb8",
        "5f7b9ce4d7b17baa6306f4e15a2b9b39bd2b27cde43446456ff9c8612dcb8232",
        "3b3e3bdcd60b2d8a43a945da48950dee65734ad6bf70c3deacebf37946fdc191",
    },
    /* 18 */
    {
        "BBBBBBBBBBBBBBB3333333333333333EEEEEEEEEEEEEEEEEE888888888888888",
        "0d2fadfb6228aab61281ac711dfc405889d654394a7afb375a82ab00c6205cb8",
        "5f7b9ce4d7b17baa6306f4e15a2b9b39bd2b27cde43446456ff9c8612dcb8232",
        "3b3e3bdcd60b2d8a43a945da48950dee65734ad6bf70c3deacebf37946fdc191",
        "e16239ba5f1f03f30da7bb9adc798db29fd47111a8f5a3fb0ec960d0bfa10600",
        "00a83dd009817949fa912bce2a125707807cf7bfb326850df1eee1d86c5647d8",
        "acf879f2d6ad976da183c668cd809885e62bedb23fbd3b1d1d8afff7896c0dda",
    },
    /* 19 */
    {
        "8720498098098AB6420CFC02C4C0C2B172C847BCB41826228aa000005ea6e643",
        "0d2fadfb6228aab61281ac711dfc405889d654394a7afb375a82ab00c6205cb8",
        "5f7b9ce4d7b17baa6306f4e15a2b9b39bd2b27cde43446456ff9c8612dcb8232",
        "3b3e3bdcd60b2d8a43a945da48950dee65734ad6bf70c3deacebf37946fdc191",
        "219a1c6f7d919b05e3dedb0f3dd0ee47ea2922509610b49194bd727e38b43c5b",
        "982c5157ab0291c9a89cc9dc759a4d54e0c84652f20d0526dc9eef49808a469b",
        "bc4c8e0c058dab335b2d5bde43e053a75e841087e54ad555e96dfea4ae5a1ae5",
    },
    /* 20 */
    {
        "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141",
        "219a1c6f7d919b05e3dedb0f3dd0ee47ea2922509610b49194bd727e38b43c5b",
        "982c5157ab0291c9a89cc9dc759a4d54e0c84652f20d0526dc9eef49808a469b",
        "bc4c8e0c058dab335b2d5bde43e053a75e841087e54ad555e96dfea4ae5a1ae5",
        "0",
        "0",
        "0",
    },
};

static int secp256k1_mul_p_test()
{
    int i;
    POINT256 r1, r2;
    BN_ULONG scalar[P256_LIMBS];

    for (i = 0; i < sizeof(mulp_test_vec) / sizeof(MULP_TEST_VEC); i++) {
        fp256_set_hex(scalar, (unsigned char*)mulp_test_vec[i].scalar, strlen((const char*)mulp_test_vec[i].scalar));
        fp256_set_hex(r1.X, (unsigned char*)mulp_test_vec[i].rx, strlen((const char*)mulp_test_vec[i].rx));
        fp256_set_hex(r1.Y, (unsigned char*)mulp_test_vec[i].ry, strlen((const char*)mulp_test_vec[i].ry));
        fp256_set_hex(r1.Z, (unsigned char*)mulp_test_vec[i].rz, strlen((const char*)mulp_test_vec[i].rz));
        fp256_set_hex(r2.X, (unsigned char*)mulp_test_vec[i].px, strlen((const char*)mulp_test_vec[i].px));
        fp256_set_hex(r2.Y, (unsigned char*)mulp_test_vec[i].py, strlen((const char*)mulp_test_vec[i].py));
        fp256_set_hex(r2.Z, (unsigned char*)mulp_test_vec[i].pz, strlen((const char*)mulp_test_vec[i].pz));
        
        if (secp256k1_point_is_on_curve(&r1) == 0) {
            printf("mul_p test %d, point r1 is not on curve\n", i+1);
            return CRYPTO_ERR;
        }
        if (secp256k1_point_is_on_curve(&r2) == 0) {
            printf("mul_p test %d, point r2 is not on curve\n", i+1);
            return CRYPTO_ERR;
        }
        
        secp256k1_scalar_mul_point(&r2, scalar, &r2);
        if (secp256k1_point_is_on_curve(&r2) == 0) {
            printf("mul_p test %d, point scalar*r2 is not on curve\n", i+1);
            return CRYPTO_ERR;
        }

        /* compare r1, r2 */
        if (secp256k1_point_cmp(&r1, &r2) != 0) {
            printf("mul_p test %d fail\n", i+1);
            return CRYPTO_ERR;
        }
    }
    
    printf("mul_p test pass\n");
    return CRYPTO_OK;
}

/********************** JACOBIAN - AFFINE **********************/
typedef struct
{
    char *X;      /* jacobian x, mont, hex */
    char *Y;      /* jacobian y, mont, hex */
    char *Z;      /* jacobian z, mont, hex */
    char *x;      /* affine x, hex */
    char *y;      /* affine y, hex */
}COORDINATE_TEST_VEC;

/* test vectors are generated by test.py */
static const COORDINATE_TEST_VEC coor_test_vec[] =
{
    /* 1 */
    {
        "1baec2e5f20f849297d9661350e1916052cfa64d4c51374c06844cf62631a8d7",
        "10eb6f079cc17c99e3fe247b1f16a0b788bffa434efdf77cec0d9e94b12e28a7",
        "d1549af286d8ac9af3a884c08711ad75432fc0251c9c427a7222fe9a3b33468a",
        "9a0bf18579853af2c53fc9870941465bb6b7694544ca09a9a6bc22928977d780",
        "25df6ca96534a2c433fd5f4f8b59db63323b68ac88faade73fffc191f3f4d750",
    },
    /* 2 */
    {
        "ec0f22095e3c6c5a5cc3b69f1f4e862ea49771c8fcacbc91340a1c3288cb7b90",
        "8b924195ae5c2ce03993e5bd00ad0d971e36bd951de377ece6f390f86a7765e9",
        "66696d34e1d61189cd96bb324c193d4637d79ab6e0108a7b7c3699c89fd67df8",
        "3dae88d93a114804cc270139b4dceb588c70e2b7439ce8777f3ac3aa5d477673",
        "191a866c21b58068b380e47c8f3b0b702357569c9693f90c8121d73b6098c24d",
    },
    /* 3 */
    {
        "258def08016958cd197b62e04e64a31e0daab2b91ba000571dc883f4f0f77f47",
        "6b387854ed659cbeb06059768b26a13bef0332ef3e1fbbef06d7fb985a8eadcf",
        "f6bd8e8fc897905af537ab709ac95d10c77fc41380cfb7a07015e213ce51c4e1",
        "6441f7b8965be96c83fe13a8eb01705d952758dd9061840dd316a3cbfb63643e",
        "9c2b8c529041d8e7359c1f6a247577a0f65bd98bf6dc044120bd74aa95a69b15",
    },
    /* 4 */
    {
        "bc3bb1640af319703d9b860b392eb96b6c4fdeffff81619d5adf75bc6b8951c3",
        "a83e04ae0e6fa24c2aba5638b5ed878c25bb990cff38ec5013c70ed22f5ca9a1",
        "139e26a35dbac899befc858f220b730f130bfcbd9d8e40832bb2120dfef0f7a2",
        "1e9116356cf3997ef71b66da5c1a593c03ec82d2e90a0cc60e288f5fa2a38384",
        "47dc3404e2abff91ffd296f6e453c92d3169bc9f14f6b8ec21efb93d4652281b",
    },
    /* 5 */
    {
        "8bfdde00ea61950fb83d8a3764f84f8b902d59fb05705e90cb152ffff178da27",
        "3c1bdbb650ad240dcbca4b292ec79357f9c5e2ddc5c89a6771ec80aef7441c67",
        "fd088648e4b25c296c58584716a521d8c22b61c8092bb781b3a9a0e5712d4616",
        "06186eca35bf7a692e1b20ea23b3c624d547bc054b9853ff932075e3cfb730aa",
        "552d5ffeed5cd3bcb93c87d28f00d054e62800d5632bce024deb94657ace5fb7",
    },
};

/* conversion between jacobian and affine coordinate test */
static int secp256k1_coor_test()
{
    int i;
    POINT256 r1, r2;
    BN_ULONG x1[P256_LIMBS], y1[P256_LIMBS];
    BN_ULONG x[P256_LIMBS], y[P256_LIMBS];

    for (i = 0; i < sizeof(coor_test_vec) / sizeof(COORDINATE_TEST_VEC); i++) {
        fp256_set_hex(r1.X, (unsigned char*)coor_test_vec[i].X, strlen((const char*)coor_test_vec[i].X));
        fp256_set_hex(r1.Y, (unsigned char*)coor_test_vec[i].Y, strlen((const char*)coor_test_vec[i].Y));
        fp256_set_hex(r1.Z, (unsigned char*)coor_test_vec[i].Z, strlen((const char*)coor_test_vec[i].Z));
        fp256_set_hex(x, (unsigned char*)coor_test_vec[i].x, strlen((const char*)coor_test_vec[i].x));
        fp256_set_hex(y, (unsigned char*)coor_test_vec[i].y, strlen((const char*)coor_test_vec[i].y));
        
        if (secp256k1_point_is_on_curve(&r1) == 0) {
            printf("coor test %d, point r1 is not on curve\n", i+1);
            return CRYPTO_ERR;
        }

        /* get affine coordinate */
        if (secp256k1_point_get_affine(x1, y1, &r1) == CRYPTO_ERR) {
            printf("coor test %d, get affine fail\n", i+1);
            return CRYPTO_ERR;
        }

        /* compare affine coordinate */
        if (fp256_cmp(x, x1) != 0 || fp256_cmp(y, y1) != 0) {
            printf("coor test %d, compare affine fail\n", i+1);
            return CRYPTO_ERR;
        }

        /* set affine coordinate */
        if (secp256k1_point_set_affine(&r2, x1, y1) == CRYPTO_ERR) {
            printf("coor test %d, set affine fail\n", i+1);
            return CRYPTO_ERR;
        }

        if (secp256k1_point_is_on_curve(&r2) == 0) {
            printf("coor test %d, point r2 is not on curve\n", i+1);
        }

        /* compare point r1, r2 */
        if (secp256k1_point_cmp(&r1, &r2) != 0) {
            printf("coor test %d, compare point fail\n", i+1);
            return CRYPTO_ERR;
        }
    }

    printf("coor test pass\n");
    return CRYPTO_OK;
}

int main(int argc, char **argv)
{
    int ret = 0;
    if (CRYPTO_init() == CRYPTO_ERR)
        return -1;

    // TEST_ARGS args;
    // args.ok = 0;
    // args.N = 12345;
    // args.num_threads = 4;
    // get_test_args(argc, argv, &args);

    if (secp256k1_mul_g_test() == CRYPTO_ERR) {
        ret = -1;
        goto end;
    }

    if (secp256k1_mul_p_test() == CRYPTO_ERR) {
        ret = -1;
        goto end;
    }

    if (secp256k1_coor_test() == CRYPTO_ERR) {
        ret = -1;
        goto end;
    }

    // TODO : add more tests

    ret = 0;
end:
    CRYPTO_deinit();
    return ret;
}